export const BATTLEFIELD_GRID_CELLS_QTY = 220;
export const BATTLEFIELD_GRID_HORIZONTAL_CELLS_QTY = 20;
export const BATTLEFIELD_GRID_VERTICAL_CELLS_QTY = 11;
export const BATTLEFIELD_ASPECT_RATIO = 5 / 3.34;
export const BATTLEFIELD_UNIT_WIDTH_FACTOR = 3;
